from enum import StrEnum


class AuditEventType(StrEnum):
    USER_CREATED = "USER_CREATED"
    USER_LOGIN = "USER_LOGIN"
    LOGIN_FAILED = "LOGIN_FAILED"
    EMAIL_VERIFICATION_SENT = "EMAIL_VERIFICATION_SENT"
    EMAIL_VERIFICATION_SEND_FAILED = "EMAIL_VERIFICATION_SEND_FAILED"
    EMAIL_VERIFIED = "EMAIL_VERIFIED"
    EMAIL_VERIFICATION_FAILED = "EMAIL_VERIFICATION_FAILED"
    PROFILE_CREATED = "PROFILE_CREATED"
    PROFILE_UPDATED = "PROFILE_UPDATED"
    FIELD_CREATED = "FIELD_CREATED"
    FIELD_UPDATED = "FIELD_UPDATED"
    FIELD_DISABLED = "FIELD_DISABLED"
    MODEL_REGISTERED = "MODEL_REGISTERED"
    MODEL_VALIDATED = "MODEL_VALIDATED"
    MODEL_REJECTED = "MODEL_REJECTED"
    MODEL_DEPLOYED = "MODEL_DEPLOYED"
    MODEL_PROMOTED = "MODEL_PROMOTED"
    MODEL_ARCHIVED = "MODEL_ARCHIVED"
    RECOMMENDATION_CREATED = "RECOMMENDATION_CREATED"
    RECOMMENDATION_FEEDBACK_ADDED = "RECOMMENDATION_FEEDBACK_ADDED"
    DRIFT_DETECTED = "DRIFT_DETECTED"
    RETRAINING_STARTED = "RETRAINING_STARTED"
    RETRAINING_COMPLETED = "RETRAINING_COMPLETED"


# Backward-compatible string constants.
globals().update({event.name: event.value for event in AuditEventType})
